# Generated by Django 5.0.6 on 2024-11-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_amaatracategory_ssmcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssmfaq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_app.ssmcategory'),
        ),
    ]
