# Generated by Django 5.0.6 on 2024-11-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0004_peshospitalcategory_pesimsrcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pucupoloadmarks',
            name='biotechnology',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pucupoloadmarks',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
