# Generated by Django 5.0.6 on 2024-11-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0005_pucupoloadmarks_biotechnology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedk',
            name='upload_marks',
            field=models.ImageField(default=None, upload_to='comedk_upload_marks/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeemain1',
            name='upload_marks',
            field=models.ImageField(default=None, upload_to='jeemain1_upload_marks/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeemain2',
            name='crl_rank',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='jeemain2',
            name='upload_marks',
            field=models.ImageField(default=None, upload_to='jeemain2_upload_marks/'),
            preserve_default=False,
        ),
    ]
