# Generated by Django 5.0.6 on 2024-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0007_alter_jeemain2_crl_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedk',
            name='upload_marks',
            field=models.ImageField(blank=True, null=True, upload_to='comedk_upload_marks/'),
        ),
        migrations.AlterField(
            model_name='jeemain1',
            name='upload_marks',
            field=models.ImageField(blank=True, null=True, upload_to='jeemain1_upload_marks/'),
        ),
        migrations.AlterField(
            model_name='jeemain2',
            name='upload_marks',
            field=models.ImageField(blank=True, null=True, upload_to='jeemain2_upload_marks/'),
        ),
    ]
