# Generated by Django 5.0.6 on 2024-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0008_alter_comedk_upload_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedk',
            name='tat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
