# Generated by Django 5.0.6 on 2024-12-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0009_comedk_tat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedk',
            name='comedk_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
